[project]
name = "my-python-project"
version = "0.1.0"
description = "my desc"
# readme = "README.md" # put back later
requires-python = ">=3.11"
license = {text = "MIT"}
authors = [
  {name = "Jesse Nieboer", email = "jessenieboer@protonmail.com"}
]

dependencies = []

[dependency-groups]
dev = [
  "pytest>=8.0"
#   "pytest-cov>=5.0",
#   "ruff>=0.9",           
#   "mypy>=1.10",
#   "pre-commit>=4.0",
]

# Tool settings
[tool.pyright]
# pyright provides both type checking and import resolution:
  # files/directories that should be analyzed for both type checking and import resolution go in "include"
  # directories that should be on the path when resolving imports go in "extraPaths"; if nothing is here, pyright will assume all packages are at the root of the project
  # files/directories that should not be analyzed at all go in "exclude"  
exclude = [
    "**/__pycache__",
    "**/.devenv",
    "**/.direnv",
    "**/.pytest_cache"
]
#extraPaths = ["src"]
followSymlinks = false # prevent recursion into the nix store?
#include = ["bdd", "src", "tests"]
reportMissingImports = "error"
reportMissingTypeAnnotation = "error"
typeCheckingMode = "strict" # change to "basic" if necessary
verboseOutput = false

# [build-system]
# requires = ["hatchling"]
# build-backend = "hatchling.build"

# [tool.ruff]
# line-length = 100
# target-version = "py311"

# [tool.ruff.lint]
# select = ["E", "F", "I", "B", "C4", "SIM", "UP"]
# ignore = []

# [tool.ruff.format]
# quote-style = "double"

# [tool.mypy]
# python_version = "3.11"
# strict = true
# warn_unused_configs = true

# [build-system]
# requires = ["hatchling"]
# build-backend = "hatchling.build"
