;; Generated by devenv task 'emacs_toolbox:generate_dir_locals_el'
;; Do not edit this file directly — it will be overwritten on shell entry.
((nil . ((eval . (load (expand-file-name ".toolboxes/ai_toolbox/ai_toolbox_setup" (project-root (project-current))) t t t)))))
