;; Generated by devenv task 'emacs_toolbox:generate-dir-locals'
;; Do not edit this file directly — it will be overwritten on shell entry.
((nil . ((eval . (load (expand-file-name "toolboxes/ai_toolbox/ai_toolbox_setup.el")
                       nil t t)))))
