[project]
name = "ai toolbox"
revision = "1.0"
# Extend configurations from subdirectories
# extends = [ "subdir1", "subdir2" ]

[profiles.default]
# DATABASE_URL = { description = "Database connection string", required = true }

[profiles.dev]
PERSONAL_WORKPLACE_TEST = { description = "test secret for personal workspace", providers = ["personal_workplace"], required = true }
XAI_API_KEY = { description = "jessenieboer's xai api key", providers = ["personal_workplace"], required = true }