{ pkgs, lib, config, inputs, ... }:
let 
envrc = ./programs/.envrc;
in
{
  config = {
    enterShell = ''
      echo "jessenieboer's emacs toolbox available"
    '';

    tasks = {
      "emacs_toolbox:copy_envrc" = {
        before = [ "devenv:enterShell" ];
        exec = ''
          if [ -f "${config.devenv.root}/.envrc" ]; then
          echo ".envrc already exists — skipping copy."
          exit 0
          fi
          cp ${envrc} ${config.devenv.root}/.envrc
          chmod u+w ${config.devenv.root}/.envrc

          echo "copied programs/envrc to .envrc"
        '';
        showOutput = true;
      };
      "emacs_toolbox:generate_dir_locals" = {
        before = [ "devenv:enterShell" ];
        exec = ''
          echo "Generating .dir-locals.el from toolboxes/*_dir_locals.el..."

          if [ ! -d "${config.devenv.root}/toolboxes" ]; then
          echo "No toolboxes/ directory found — skipping."
          exit 0
          fi

          cat > ${config.devenv.root}/.dir-locals.el << 'EOF'
          ;; Generated by devenv task 'emacs_toolbox:generate-dir-locals'
          ;; Do not edit this file directly — it will be overwritten on shell entry.
          EOF

          find toolboxes -type f -name '*_dir_locals.el' -print0 \
          | sort -z \
          | xargs -0 cat >> ${config.devenv.root}/.dir-locals.el

          echo "✓ Generated .dir-locals.el from $(find toolboxes -name '*_dir_locals.el' | wc -l) files"
        '';
        showOutput = true;
      };
      "devenv:enterShell".after = [ "emacs_toolbox:generate_dir_locals" ];
    };
  };
}
