{ pkgs, lib, config, inputs, ... }:
let 
envrc = ./programs/.envrc;
in
{
  config = {
    # note that this must run after all other tasks in other devenv.nix files (because those tasks copy their own dir_locals files that need to be combined)
    enterShell = lib.mkAfter ''
      echo "Generating .dir-locals.el from toolboxes/*dir_locals..."
      if [ ! -d "${config.devenv.root}/toolboxes" ]; then
      echo "No toolboxes/ directory found — skipping."
      exit 0
      fi

      cat > ${config.devenv.root}/.dir-locals.el << 'EOF'
      ;; Generated by devenv task 'emacs_toolbox:generate_dir_locals_el'
      ;; Do not edit this file directly — it will be overwritten on shell entry.
      EOF

      files=$(find toolboxes -type f -name '*dir_locals' | sort)

      if [ -z "$files" ]; then
      echo "No *dir_locals files found."
      exit 0
      fi

      printf '%s\n' "$files" | xargs cat >> ${config.devenv.root}/.dir-locals.el

      echo "✓ Generated .dir-locals.el from:"
      printf '%s\n' "$files" | sed 's|^|  - |'
      echo "jessenieboer's emacs toolbox available"
    '';

    tasks = {
      "emacs_toolbox:copy_envrc" = {
        before = [ "devenv:enterShell" ];
        exec = ''
          if [ -f "${config.devenv.root}/.envrc" ]; then
          echo ".envrc already exists — skipping copy."
          exit 0
          fi
          cp ${envrc} ${config.devenv.root}/.envrc
          chmod u+w ${config.devenv.root}/.envrc

          echo "copied programs/envrc to .envrc"
        '';
        showOutput = true;
      };
      # "emacs_toolbox:generate_dir_locals_el" = {
      #   after = [ "devenv:enterShell" ];
      #   exec = ''
      #     echo "Generating .dir-locals.el from toolboxes/*dir_locals..."
      #     if [ ! -d "${config.devenv.root}/toolboxes" ]; then
      #     echo "No toolboxes/ directory found — skipping."
      #     exit 0
      #     fi

      #     cat > ${config.devenv.root}/.dir-locals.el << 'EOF'
      #     ;; Generated by devenv task 'emacs_toolbox:generate_dir_locals_el'
      #     ;; Do not edit this file directly — it will be overwritten on shell entry.
      #     EOF

      #     files=$(find toolboxes -type f -name '*dir_locals' | sort)

      #     if [ -z "$files" ]; then
      #     echo "No *dir_locals files found."
      #     exit 0
      #     fi

      #     printf '%s\n' "$files" | xargs cat >> ${config.devenv.root}/.dir-locals.el

      #     echo "✓ Generated .dir-locals.el from:"
      #     printf '%s\n' "$files" | sed 's|^|  - |'
      #   '';
      #   showOutput = true;
      # };
    };
  };
}
