[project]
name = "secrets"
revision = "1.0"
# Extend configurations from subdirectories
# extends = [ "subdir1", "subdir2" ]

[profiles.default]
#TEST_LOGIN = { description = "test login", providers = ["shared"], required = true }

[profiles.development]
TEST_LOGIN = { description = "test login", providers = ["shared"], required = true }
