[project]
name = "secrets_toolbox"
revision = "1.0"
# Extend configurations from subdirectories
# extends = [ "subdir1", "subdir2" ]

[profiles.default]

[profiles.dev]
PERSONAL_WORKPLACE_TEST = { description = "test secret for personal workspace", providers = ["personal_workplace"], required = true }