[project]
name = "secrets_toolbox"
revision = "1.0"
# Extend configurations from subdirectories
# extends = [ "subdir1", "subdir2" ]

[profiles.default]

[profiles.dev]
XAI_API_KEY = { description = "jessenieboer's xai api key", providers = ["personal_workplace"], required = true }