[project]
name = "home-manager"
revision = "1.0"

[providers]
bws_home_manager = { uri = "bws://ff39ba56-1bfb-46cf-af64-b42601032d0f", credentials = { access_token = "bws_access_token" } }
bws_access_token = "pass://jessenieboer_secretspec_bws_access_token"

[profiles.default]
XAI_API_KEY = { description = "jessenieboer's xai api key", required = true }

[profiles.default.defaults]
providers = ["bws_home_manager"]
