# note: copy to ~/.config/emacs
[project]
name = "home-manager"
revision = "1.0"

[profiles.default]
XAI_API_KEY = { description = "jessenieboer's xai api key", required = true }

[profiles.default.defaults]
providers = ["jessenieboer_home_manager"] # defined in global config in ~/.config/secretspec/config.toml
