((nil . ((org-agenda-custom-commands . (;; curation views
  					("\\" "Hard Dates Check" ((tags "FREQUENCY=\"once\"&HAS_HARD_START_DATE=\"\"|FREQUENCY=\"once\"&HAS_HARD_DUE_DATE=\"\"" ((org-agenda-overriding-header "Does this task have any hard dates we need to be aware of?") (org-agenda-skip-function 'pmt-skip-references) (org-agenda-sorting-strategy '((tags deadline-up))))) (tags "FREQUENCY=\"repetitive\"&HAS_HARD_START_DATE=\"\"|FREQUENCY=\"repetitive\"&HAS_HARD_DUE_DATE=\"\"" ((org-agenda-overriding-header "Does this routine have any hard dates we need to be aware of?") (org-agenda-skip-function 'pmt-skip-references) (org-agenda-sorting-strategy '((tags deadline-up)))))) ((org-overriding-columns-format "%20ITEM(Task/Occurance) %HAS_HARD_START_DATE(Hstrt?) %SCHEDULED(Start date) %HAS_HARD_DUE_DATE(Hdue?) %DEADLINE(Due date) %10CATEGORY(Project)") (org-agenda-view-columns-initially t)))
  					("w" "Hard Scheduling" ((tags "FREQUENCY=\"once\"&HAS_HARD_START_DATE=\"yes\"|FREQUENCY=\"once\"&HAS_HARD_DUE_DATE=\"yes\"" ((org-agenda-overriding-header "What hard dates do we know about?") (org-agenda-skip-function 'pmt-skip-references) (org-agenda-sorting-strategy '((tags deadline-up))))) (tags "FREQUENCY=\"repetitive\"&HAS_HARD_START_DATE=\"yes\"|FREQUENCY=\"repetitive\"&HAS_HARD_DUE_DATE=\"yes\"" ((org-agenda-overriding-header "What hard dates do we know about?") (org-agenda-skip-function 'pmt-skip-references) (org-agenda-sorting-strategy '((tags deadline-up)))))) ((org-overriding-columns-format "%20ITEM(Task/Occurance) %HAS_HARD_START_DATE(Hstrt?) %SCHEDULED(Start date) %HAS_HARD_DUE_DATE(Hdue?) %DEADLINE(Due date) %10CATEGORY(Project)") (org-agenda-view-columns-initially t)))
  					("[" "Missing Hard Dates" ((tags "FREQUENCY=\"once\"&HAS_HARD_START_DATE=\"yes\"&SCHEDULED=\"\"|FREQUENCY=\"once\"&HAS_HARD_DUE_DATE=\"yes\"&DEADLINE=\"\"" ((org-agenda-overriding-header "What hard dates are we missing?") (org-agenda-skip-function 'pmt-skip-references) (org-agenda-sorting-strategy '((tags deadline-up))))) (tags "FREQUENCY=\"repetitive\"&HAS_HARD_START_DATE=\"yes\"&SCHEDULED=\"\"|FREQUENCY=\"repetitive\"&HAS_HARD_DUE_DATE=\"yes\"&DEADLINE=\"\"" ((org-agenda-overriding-header "What hard dates are we missing?") (org-agenda-skip-function 'pmt-skip-references) (org-agenda-sorting-strategy '((tags deadline-up)))))) ((org-overriding-columns-format "%20ITEM(Task/Occurance) %HAS_HARD_START_DATE(Hstrt?) %SCHEDULED(Start date) %HAS_HARD_DUE_DATE(Hdue?) %DEADLINE(Due date) %10CATEGORY(Project)") (org-agenda-view-columns-initially t)))
  					;;("[" "All Dependencies" tags "*" ((org-overriding-columns-format "%7TODO(Status) %30ITEM(Task) %HARD_INTERNAL_DEPENDENCY(Hard Int) %SOFT_INTERNAL_DEPENDENCY(Soft Int) %HARD_EXTERNAL_DEPENDENCY(Hard Ext) %SOFT_EXTERNAL_DEPENDENCY(Soft Ext) %15CATEGORY(Project)") (org-agenda-overriding-header "Are there dependencies for these tasks?") (org-agenda-skip-function 'pmt-skip-non-tasks) (org-agenda-sorting-strategy '((tags category-up))) (org-agenda-view-columns-initially t)))
  					("g" "Relevant Dependencies" ((tags "FREQUENCY=\"once\"&DEADLINE<=\"<+1m>\"|FREQUENCY=\"once\"&TACTICAL_VALUE=\"more\"&DEADLINE=\"\"|FREQUENCY=\"once\"&TODO=\"next\"|FREQUENCY=\"once\"&TODO=\"now\"" ((org-agenda-overriding-header "Are there any tasks that should or must be done prior to this?") (org-agenda-skip-function 'pmt-skip-non-tasks) (org-agenda-sorting-strategy '((tags category-up))))) (tags "FREQUENCY=\"repetitive\"&DEADLINE<=\"<+1m>\"|FREQUENCY=\"repetitive\"&TACTICAL_VALUE=\"more\"&DEADLINE=\"\"|FREQUENCY=\"repetitive\"&TODO=\"next\"|FREQUENCY=\"repetitive\"&TODO=\"now\"" ((org-agenda-overriding-header "Are there any tasks that should or must be done prior to this?") (org-agenda-skip-function 'pmt-skip-non-tasks) (org-agenda-sorting-strategy '((tags category-up))))) (tags "FREQUENCY=\"continuous\"&DEADLINE<=\"<+1m>\"|FREQUENCY=\"continuous\"&TACTICAL_VALUE=\"more\"&DEADLINE=\"\"|FREQUENCY=\"continuous\"&TODO=\"next\"|FREQUENCY=\"continuous\"&TODO=\"now\"" ((org-agenda-overriding-header "Are there any tasks that should or must be done prior to this?") (org-agenda-skip-function 'pmt-skip-non-tasks) (org-agenda-sorting-strategy '((tags category-up)))))) ((org-agenda-view-columns-initially t) (org-overriding-columns-format "%30ITEM(Task) %HARD_INTERNAL_DEPENDENCY(Hard Int) %SOFT_INTERNAL_DEPENDENCY(Soft Int) %HARD_EXTERNAL_DEPENDENCY(Hard Ext) %SOFT_EXTERNAL_DEPENDENCY(Soft Ext) %15CATEGORY(Project)")))
  					;;("l" "Strategic Evaluation" ((tags "FREQUENCY=\"once\"" ((org-agenda-cmp-user-defined 'pmt-org-cmp-tactical-value) (org-agenda-overriding-header "How beneficial would this task be if all tasks were finished?") (org-agenda-skip-function 'pmt-skip-non-tasks) (org-agenda-sorting-strategy '((tags user-defined-down))))) (tags "FREQUENCY=\"repetitive\"" ((org-agenda-cmp-user-defined 'pmt-org-cmp-tactical-value) (org-agenda-overriding-header "How beneficial would this routine be if all routines were finished?") (org-agenda-skip-function 'pmt-skip-non-tasks) (org-agenda-sorting-strategy '((tags user-defined-down))))) (tags "FREQUENCY=\"continuous\"" ((org-agenda-cmp-user-defined 'pmt-org-cmp-tactical-value) (org-agenda-overriding-header "How beneficial would this practice be if all were practiced?") (org-agenda-skip-function 'pmt-skip-non-tasks) (org-agenda-sorting-strategy '((tags user-defined-down)))))) ((org-agenda-view-columns-initially t) (org-overriding-columns-format "%STRATEGIC_VALUE(Strat Val) %30ITEM(Task) %17DEADLINE(Due date) %5HAS_HARD_DUE_DATE(Hard?) %15CATEGORY(Project)")))
  					("l" "Tactical Evaluation" ((tags "HAS_HARD_START_DATE=\"no\"|HAS_HARD_START_DATE=\"yes\"&SCHEDULED<=\"<+1w>\"|HAS_HARD_START_DATE=\"yes\"&SCHEDULED<=\"\"" ((org-agenda-cmp-user-defined 'pmt-org-cmp-tactical-value) (org-agenda-overriding-header "How beneficial would this task be if it were finished now?") (org-agenda-skip-function 'pmt-skip-non-tasks) (org-agenda-sorting-strategy '((tags category-up user-defined-down deadline-up)))))) ((org-agenda-view-columns-initially t) (org-overriding-columns-format "%TACTICAL_VALUE(Tac Val) %30ITEM(Task)  %15CATEGORY(Project)")))
  					("a" "Effort Estimation" ((tags "DEADLINE<=\"<+1m>\"|TACTICAL_VALUE<>\"less\"&DEADLINE=\"\"|TODO=\"next\"|TODO=\"now\"" ((org-agenda-cmp-user-defined 'pmt-org-cmp-estimated-effort) (org-agenda-overriding-header "How much of our effort would it take to finish this task now?") (org-agenda-skip-function 'pmt-skip-all-dependent-tasks) (org-agenda-sorting-strategy '((tags category-up user-defined-up)))))) ((org-agenda-view-columns-initially t) (org-overriding-columns-format "%ESTIMATED_EFFORT(Effort) %30ITEM(Task) %15CATEGORY(Project)")))
					("r" "Soft Scheduling" ((tags "FREQUENCY=\"once\"&HAS_HARD_START_DATE=\"no\"&HAS_HARD_DUE_DATE=\"no\"&TACTICAL_VALUE=\"more\"|FREQUENCY=\"once\"&HAS_HARD_START_DATE=\"no\"&HAS_HARD_DUE_DATE=\"no\"&ESTIMATED_EFFORT=\"less\"&TACTICAL_VALUE<>\"less\"" ((org-agenda-overriding-header "Do we want to tentatively schedule any tasks?") (org-agenda-skip-function 'pmt-skip-all-dependent-tasks) (org-agenda-sorting-strategy '((tags category-up deadline-up))))) (tags "FREQUENCY=\"repetitive\"&HAS_HARD_START_DATE=\"no\"&HAS_HARD_DUE_DATE=\"no\"&TACTICAL_VALUE=\"more\"|FREQUENCY=\"repetitive\"&HAS_HARD_START_DATE=\"no\"&HAS_HARD_DUE_DATE=\"no\"&ESTIMATED_EFFORT=\"less\"" ((org-agenda-overriding-header "Do we want to tentatively schedule any routines?") (org-agenda-skip-function 'pmt-skip-all-dependent-tasks) (org-agenda-sorting-strategy '((tags category-up deadline-up)))))) ((org-overriding-columns-format "%20ITEM(Task) %SCHEDULED(Start date) %DEADLINE(Due date) %10CATEGORY(Project)") (org-agenda-view-columns-initially t)))
  					("t" "Activity" ((tags "DEADLINE<=\"<+1w>\"" ((org-agenda-overriding-header "When are these things happening?") (org-agenda-skip-function 'pmt-skip-non-occurrences) (org-agenda-sorting-strategy '((tags category-up deadline-up))))) (tags "FREQUENCY=\"once\"&DEADLINE<=\"<+1w>\"|FREQUENCY=\"once\"&TACTICAL_VALUE=\"more\"&DEADLINE=\"\"|FREQUENCY=\"once\"&ESTIMATED_EFFORT=\"less\"&TACTICAL_VALUE<>\"less\"&DEADLINE=\"\"" ((org-agenda-cmp-user-defined 'pmt-org-cmp-estimated-effort) (org-agenda-overriding-header "When are we doing these tasks?") (org-agenda-skip-function 'pmt-skip-all-dependent-tasks) (org-agenda-sorting-strategy '((tags category-up user-defined-up))))) (tags "FREQUENCY=\"repetitive\"&DEADLINE<=\"<+1w>\"|FREQUENCY=\"repetitive\"&TACTICAL_VALUE=\"more\"&DEADLINE=\"\"|FREQUENCY=\"repetitive\"&ESTIMATED_EFFORT=\"less\"&TACTICAL_VALUE<>\"less\"&DEADLINE=\"\"" ((org-agenda-cmp-user-defined 'pmt-org-cmp-estimated-effort) (org-agenda-overriding-header "When are we doing these routines?") (org-agenda-skip-function 'pmt-skip-all-dependent-tasks) (org-agenda-sorting-strategy '((tags category-up user-defined-up))))) (tags "FREQUENCY=\"continuous\"&TACTICAL_VALUE=\"more\"|FREQUENCY=\"continuous\"&ESTIMATED_EFFORT=\"less\"" ((org-agenda-cmp-user-defined 'pmt-org-cmp-estimated-effort) (org-agenda-overriding-header "When are we doing these practices?") (org-agenda-skip-function 'pmt-skip-all-dependent-tasks) (org-agenda-sorting-strategy '((tags category-up user-defined-up)))))) ((org-agenda-view-columns-initially t) (org-overriding-columns-format "%7TODO(When) %30ITEM(Task) %TACTICAL_VALUE(Tac Val) %ESTIMATED_EFFORT(Effort) %17DEADLINE(Due date) %5HAS_HARD_DUE_DATE(Hard?) %15CATEGORY(Project)")))
  					;;reporting views
  					;;("q" "Basics" tags "*" ((org-overriding-columns-format "%7TODO(Status) %30ITEM(Task) %FREQUENCY(Freq) %HAS_HARD_START_DATE(Hard start?) %HAS_HARD_DUE_DATE(Hard due?) %15CATEGORY(Project)") (org-agenda-overriding-header "What are the basics?") (org-agenda-skip-function 'pmt-skip-references) (org-agenda-view-columns-initially t)))
  					("s" "Focus" ((tags "TODO=\"now\"" ((org-agenda-overriding-header "What occurrences are we focusing on?") (org-agenda-skip-function 'pmt-skip-non-occurrences) (org-agenda-sorting-strategy '((tags deadline-up))))) (tags "FREQUENCY=\"once\"&TODO=\"now\"" ((org-agenda-cmp-user-defined 'pmt-org-cmp-estimated-effort) (org-agenda-overriding-header "What tasks are we focusing on?") (org-agenda-skip-function 'pmt-skip-all-dependent-tasks) (org-agenda-sorting-strategy '((tags user-defined-up))))) (tags "FREQUENCY=\"repetitive\"&TODO=\"now\"" ((org-agenda-cmp-user-defined 'pmt-org-cmp-estimated-effort) (org-agenda-overriding-header "What routines are we focusing on?") (org-agenda-skip-function 'pmt-skip-all-dependent-tasks) (org-agenda-sorting-strategy '((tags user-defined-up))))) (tags "FREQUENCY=\"continuous\"&TODO=\"now\"" ((org-agenda-cmp-user-defined 'pmt-org-cmp-estimated-effort) (org-agenda-overriding-header "What practices are we focusing on?") (org-agenda-skip-function 'pmt-skip-all-dependent-tasks) (org-agenda-sorting-strategy '((tags category-up user-defined-up)))))) ((org-agenda-view-columns-initially t) (org-overriding-columns-format "%7TODO(Status) %30ITEM(Task) %ESTIMATED_EFFORT(Effort) %15CATEGORY(Project)")))
  					("e" "Calendar" agenda "SCHEDULED<>\"\"|DEADLINE<>\"\"" ((org-agenda-include-deadlines t) (org-agenda-overriding-header "What's on the calendar?") (org-agenda-prefix-format '((agenda . "%?-t "))) (org-agenda-skip-function 'pmt-skip-top-level-headlines) (org-agenda-skip-deadline-prewarning-if-scheduled 'pre-scheduled) (org-agenda-skip-scheduled-if-deadline-is-shown t) (org-agenda-sorting-strategy '((tags deadline-up))) (org-agenda-span 'week) (org-agenda-todo-keyword-format "%-7s") (org-agenda-use-time-grid nil) (org-deadline-warning-days 1)) ("/home/jessenieboer/kingdoms/Household/Jesse/personal_workplace/toolboxes/project_management/calendar.html" "/home/jessenieboer/kingdoms/Household/Jesse/personal_workplace/toolboxes/project_management/calendar.ps" "/home/jessenieboer/kingdoms/Household/Jesse/personal_workplace/toolboxes/project_management/calendar.ics"))
  					;;("n" "Dependent Tasks" tags "HARD_INTERNAL_DEPENDENCY=\"yes\"|SOFT_INTERNAL_DEPENDENCY=\"yes\"|HARD_EXTERNAL_DEPENDENCY=\"yes\"|SOFT_EXTERNAL_DEPENDENCY=\"yes\"" ((org-overriding-columns-format "%7TODO(Status) %30ITEM(Task) %HARD_INTERNAL_DEPENDENCY(Hard Int) %SOFT_INTERNAL_DEPENDENCY(Soft Int) %HARD_EXTERNAL_DEPENDENCY(Hard Ext) %SOFT_EXTERNAL_DEPENDENCY(Soft Ext) %15CATEGORY(Project)") (org-agenda-overriding-header "What tasks have outstanding dependencies?") (org-agenda-skip-function 'pmt-skip-non-tasks) (org-agenda-sorting-strategy '((tags alpha-up))) (org-agenda-view-columns-initially t)))
  					("c" "Past items" tags "TODO=\"past\"" ((org-agenda-overriding-header "What have we done?") (org-agenda-skip-function 'pmt-skip-top-level-headlines) (org-agenda-skip-function-global nil) (org-agenda-sorting-strategy '((tags category-up))) (org-agenda-view-columns-initially t) (org-overriding-columns-format "%7TODO(Status) %30ITEM(Task) %15CATEGORY(Project)")))
  					;;("," "All Items" tags "*" ((org-agenda-overriding-header "What are all the items in project_management_toolbox?") (org-agenda-prefix-format '((tags . ""))) (org-agenda-skip-function 'pmt-skip-top-level-headlines) (org-agenda-sorting-strategy '((tags alpha-up)))) ("@PROJECT_DIRECTORY@project/test.html" "@PROJECT_DIRECTORY@project/test.ps" "@PROJECT_DIRECTORY@project/test.ics"))
  					))
    	 (org-agenda-files . ("/home/jessenieboer/kingdoms/Household/Jesse/personal_workplace/toolboxes/project_management/project_management_toolbox.org" ))
    	 (org-archive-location . "%s_archive::")
    	 (org-archive-mark-done . t)
    	 (org-capture-templates . (("s" "Task" entry
    				    (file+headline "project_management_toolbox.org" "Tasks")
    				    "* future %^{Title}\n:PROPERTIES:\n:CATEGORY: project_management_toolbox\n:FREQUENCY: once\n:HAS_HARD_START_DATE: no\n:HAS_HARD_DUE_DATE: no\n:HARD_INTERNAL_DEPENDENCY: no \n:SOFT_INTERNAL_DEPENDENCY: no \n:HARD_EXTERNAL_DEPENDENCY: no \n:SOFT_EXTERNAL_DEPENDENCY: no \n:STRATEGIC_VALUE: average\n:TACTICAL_VALUE: average\n:ESTIMATED_EFFORT: average\n:ESTIMATED_$_COST: trivial\n:ACTUAL_EFFORT: \n:ACTUAL_$_COST: \n:END:\n%?")
				   ("y" "--Imminent task" entry
    				    (file+headline "project_management_toolbox.org" "Tasks")
    				    "* now %^{Title}\n:PROPERTIES:\n:CATEGORY: project_management_toolbox\n:FREQUENCY: once\n:HAS_HARD_START_DATE: no\n:HAS_HARD_DUE_DATE: no\n:HARD_INTERNAL_DEPENDENCY: no \n:SOFT_INTERNAL_DEPENDENCY: no \n:HARD_EXTERNAL_DEPENDENCY: no \n:SOFT_EXTERNAL_DEPENDENCY: no \n:STRATEGIC_VALUE: average\n:TACTICAL_VALUE: more\n:ESTIMATED_EFFORT: average\n:ESTIMATED_$_COST: trivial\n:ACTUAL_EFFORT: \n:ACTUAL_$_COST: \n:END:\n%?")
    				   ("\t" "--Time-bound task" entry
    				    (file+headline "project_management_toolbox.org" "Tasks")
    				    "* future %^{Title}\n:PROPERTIES:\n:CATEGORY: project_management_toolbox\n:FREQUENCY: once\n:HAS_HARD_START_DATE: no\n:HAS_HARD_DUE_DATE: yes\n:HARD_INTERNAL_DEPENDENCY: no \n:SOFT_INTERNAL_DEPENDENCY: no \n:HARD_EXTERNAL_DEPENDENCY: no \n:SOFT_EXTERNAL_DEPENDENCY: no \n:STRATEGIC_VALUE: average\n:TACTICAL_VALUE: average\n:ESTIMATED_EFFORT: average\n:ESTIMATED_$_COST: trivial\n:ACTUAL_EFFORT: \n:ACTUAL_$_COST: \n:END:\n%?")
    				   ("e" "Routine" entry
    				    (file+headline "project_management_toolbox.org" "Tasks")
    				    "* future %^{Title}\n:PROPERTIES:\n:CATEGORY: project_management_toolbox\n:FREQUENCY: repetitive\n:HAS_HARD_START_DATE: no\n:HAS_HARD_DUE_DATE: no\n:HARD_INTERNAL_DEPENDENCY: no \n:SOFT_INTERNAL_DEPENDENCY: no \n:HARD_EXTERNAL_DEPENDENCY: no \n:SOFT_EXTERNAL_DEPENDENCY: no \n:STRATEGIC_VALUE: average\n:TACTICAL_VALUE: average\n:ESTIMATED_EFFORT: average\n:ESTIMATED_$_COST: trivial\n:ACTUAL_EFFORT: \n:ACTUAL_$_COST: \n:END:\n%?")
    				   ("i" "--Time-bound routine" entry
    				    (file+headline "project_management_toolbox.org" "Tasks")
    				    "* future %^{Title}\n:PROPERTIES:\n:CATEGORY: project_management_toolbox\n:FREQUENCY: repetitive\n:HAS_HARD_START_DATE: no\n:HAS_HARD_DUE_DATE: yes\n:HARD_INTERNAL_DEPENDENCY: no \n:SOFT_INTERNAL_DEPENDENCY: no \n:HARD_EXTERNAL_DEPENDENCY: no \n:SOFT_EXTERNAL_DEPENDENCY: no \n:STRATEGIC_VALUE: average\n:TACTICAL_VALUE: average\n:ESTIMATED_EFFORT: average\n:ESTIMATED_$_COST: trivial\n:ACTUAL_EFFORT: \n:ACTUAL_$_COST: \n:END:\n%?")
    				   ("z" "Practice" entry
      				    (file+headline "project_management_toolbox.org" "Tasks")
      				    "* future %^{Title}\n:PROPERTIES:\n:CATEGORY: project_management_toolbox\n:FREQUENCY: continuous\n:HAS_HARD_START_DATE: no\n:HAS_HARD_DUE_DATE: no\n:HARD_INTERNAL_DEPENDENCY: no \n:SOFT_INTERNAL_DEPENDENCY: no \n:HARD_EXTERNAL_DEPENDENCY: no \n:SOFT_EXTERNAL_DEPENDENCY: no \n:STRATEGIC_VALUE: average\n:TACTICAL_VALUE: average\n:ESTIMATED_EFFORT: average\n:ESTIMATED_$_COST: trivial\n:ACTUAL_EFFORT: \n:ACTUAL_$_COST: \n:END:\n%?")
    				   ("n" "Occurrence" entry
    				    (file+headline "project_management_toolbox.org" "Occurrences")
    				    "* future %^{Title}\n:PROPERTIES:\n:CATEGORY: project_management_toolbox\n:FREQUENCY: once\n:HAS_HARD_START_DATE: no\n:HAS_HARD_DUE_DATE: yes\n:HARD_INTERNAL_DEPENDENCY: no \n:SOFT_INTERNAL_DEPENDENCY: no \n:HARD_EXTERNAL_DEPENDENCY: no \n:SOFT_EXTERNAL_DEPENDENCY: no \n:STRATEGIC_VALUE: average\n:TACTICAL_VALUE: average\n:ESTIMATED_EFFORT: average\n:ESTIMATED_$_COST: trivial\n:ACTUAL_EFFORT: \n:ACTUAL_$_COST: \n:END:\n%?")
    				   ("p" "Recurrence" entry
      				    (file+headline "project_management_toolbox.org" "Occurrences")
      				    "* future %^{Title}\n:PROPERTIES:\n:CATEGORY: project_management_toolbox\n:FREQUENCY: repetitive\n:HAS_HARD_START_DATE: no\n:HAS_HARD_DUE_DATE: yes\n:HARD_INTERNAL_DEPENDENCY: no \n:SOFT_INTERNAL_DEPENDENCY: no \n:HARD_EXTERNAL_DEPENDENCY: no \n:SOFT_EXTERNAL_DEPENDENCY: no \n:STRATEGIC_VALUE: average\n:TACTICAL_VALUE: average\n:ESTIMATED_EFFORT: average\n:ESTIMATED_$_COST: trivial\n:ACTUAL_EFFORT: \n:ACTUAL_$_COST: \n:END:\n%?")
    				   ("c" "Reference" entry
    				    (file+headline "project_management_toolbox.org" "References")
    				    "* %^{Title}\n:PROPERTIES:\n:CATEGORY: project_management_toolbox\n:END:\n%?")
    				   ("b" "Journal entry" plain
    				    (file+olp+datetree "journal.org")
    				    "%?")
    				   ("h" "User story" entry
    				    (file+headline "project_management_toolbox.org" "User stories")
    				    "* future %^{Title}\n:PROPERTIES:\n:CATEGORY: project_management_toolbox\n:FREQUENCY: once\n:HAS_HARD_START_DATE: no\n:HAS_HARD_DUE_DATE: no\n:HARD_INTERNAL_DEPENDENCY: no \n:SOFT_INTERNAL_DEPENDENCY: no \n:HARD_EXTERNAL_DEPENDENCY: no \n:SOFT_EXTERNAL_DEPENDENCY: no \n:STRATEGIC_VALUE: average\n:TACTICAL_VALUE: average\n:ESTIMATED_EFFORT: average\n:ESTIMATED_$_COST: trivial\n:ACTUAL_EFFORT: \n:ACTUAL_$_COST: \n:END:\n%?")
    				   ("o" "Idea" item
    				    (file+headline "project_management_toolbox.org" "Ideas")
    				    "%^{Title}\n" :immediate-finish t)))
  	 (org-directory . "/home/jessenieboer/kingdoms/Household/Jesse/personal_workplace/toolboxes/project_management/")
    	 ;; (org-priority-highest . 2)
    	 ;; (org-priority-default . 2)
    	 ;; (org-priority-lowest . 2)
    	 (org-global-properties . (("FREQUENCY_ALL" . "once repetitive continuous")
    				   ("HAS_HARD_START_DATE_ALL" . "no yes")
          			   ("HAS_HARD_DUE_DATE_ALL" . "no yes")
    				   ("HAS_SOFT_START_DATE_ALL" . "no yes")
          			   ("HAS_SOFT_DUE_DATE_ALL" . "no yes")
    				   ;; SCHEDULED functions as start date
          			   ;; DEADLINE functions as due date
    				   ("HARD_INTERNAL_DEPENDENCY_ALL" . "no yes")
    				   ("SOFT_INTERNAL_DEPENDENCY_ALL" . "no yes")
    				   ("HARD_EXTERNAL_DEPENDENCY_ALL" . "no yes")
    				   ("SOFT_EXTERNAL_DEPENDENCY_ALL" . "no yes")
    				   ("STRATEGIC_VALUE_ALL" . "less average more")
    				   ("TACTICAL_VALUE_ALL" . "less average more")
    				   ("ESTIMATED_EFFORT_ALL" . "less average more")
          			   ;; ("ESTIMATED_EFFORT_ALL" . "1h 4h 1d 2d 3d 5d 8d 13d 21d 34d 55d 89d 144d 233d")
          			   ("ESTIMATED_$_COST_ALL" . "trivial small medium large")
          			   ("ACTUAL_EFFORT")
          			   ;; ("ACTUAL_$_COST")
    				   ))
	 ;; (org-refile-targets . '((org-agenda-files :level . 1)))
  	 (project-name . "project_management_toolbox"))))
